Cli tool anonymizer
VukW/GaNDLF pull request #1
Opened 2024-03-12 22:23 UTC by VukW

sub-PR for https://github.com/mlcommons/GaNDLF/pull/818 : adding `gandlf anonymizer` subcommand

[x] Code is here, both new way (via `gandlf` cli tool) and old way (via `gandlf_*` entrypoint) are supported
[x] Tests are here
[x] Docs are fixed

2024-03-13 16:50 UTC, sarthakpati requested changes
Minor comment but looks good otherwise!

2024-03-13 16:50 UTC, sarthakpati commented on GANDLF/entrypoints/anonymizer.py
> +        config = None
This is just to improve code coverage

```suggestion
    config = None
    if config_path and os.path.isfile(config_path):
        config = yaml.safe_load(open(config_path, "r"))

    assert config is not None, "A valid config file should be passed"
```

2024-03-26 12:59 UTC, VukW commented on GANDLF/entrypoints/anonymizer.py
> +        config = None
Are you sure we want to require config file from users?
Actually, according to the [anonymizer code](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/anonymize/__init__.py#L21) , it's ok if config is empty / not passed at all

2024-03-26 13:40 UTC, sarthakpati commented on GANDLF/entrypoints/anonymizer.py
> +        config = None
Got it, thanks for the reminder. In that case, I think the `assert` portion of my suggestion can be removed. That should be the same as before, right? 😄

2024-03-26 13:45 UTC, VukW commented on GANDLF/entrypoints/anonymizer.py
> +        config = None
Right! Commited changes:)

2024-03-26 13:49 UTC, sarthakpati approved these changes

2024-03-29 13:21 UTC, sarthakpati approved these changes

2024-06-24 19:49 UTC, closed without merging